imgix/imgix.js

src/core.js
tests/test.js

I'd like to propose this patch: allow `imgix.fluid` to take an optional first param representing a DOM node to operate on, e.g. `imgix.fluid(htmlElement, config)`.
Operating on the entire document is often overkill; our use case is a React app where the jQuery-style "run this function over a document-wide selector" is an anti-pattern. The ability to scope `fluid` to individual nodes means we can attach an `onLoad` handler that's bound to a node's corresponding React component.

Allow imgix.fluid() to operate on individual nodes instead of entire document

---

src/core.js

This patch fixes a bug reported by @ventayol. Turns out our old pal Safari (desktop and mobile) actually unsets and resets the `src` attribute of an image, even if the old and new values are identical. This causes images to flash on scroll when set to lazy-load.
cc @ventayol

Fix Safari flashing

---

src/core.js
tests/test.js

This PR fixes a gnarly bug that can lead to unexpected requests for (sometimes massive) image files. This occurs for elements that have been marked as `fluid` when it tag or any of its parents are set to `display:none;`.
The root cause here is that the mechanism used to determine an element's dimensions in `imgix.calculateElementSize()` (https://github.com/imgix/imgix.js/blob/fix-displaynone/src/core.js#L240-L267) reports `{width:0, height: 0}` for all hidden elements. When the function detemines that the element being measured has no height or width, it proceeds up the chain until an un-hidden element is found, usually the `<body>` tag. Once a visible element is found, its dimensions are used to request an image and we end up with requests for images that match the width of the entire …

Fix `display:none;` bug

---

src/core.js
tests/test.js

This will let us track usage on our backend and better isolate bugs in the future.
Quick sanity-check: @kellysutton?

Add method to include imgix.js version in requests

---

src/core.js

Setting `img.src` before `img.onload` means the callback won't fire in certain cases, such as when the image is already in the browser cache (see http://stackoverflow.com/a/5933319).
Assuming it's not intentional, here's a patch. And if it is, can I ask about the use case?

Set onload prior to src to ensure callback is run

---

src/core.js

This PR switches our lazyLoad method to use a throttle instead of a debounce, which will improve perceived performance by loading in images *as* the user scrolls, instead of waiting until scrolling has finished.
This PR also fixes a bug in the way lazy-loaded images determine whether or not they're in-viewport. Images that haven't yet loaded report their height and width as 0, which was causing images clipped by the top or right sides of the viewport to mark themselves as "do not load".
cc @gitmiggi
This codepen has the new version of the code in action: http://codepen.io/jayeb/pen/YXNqdO
Fixes #30

Throttle lazyload

---

src/core.js

Naively swapping in `window.btoa` as a way of "hashing" a URL after I stripped out the MD5 stuff last week turns out to have been a terrible idea!
This PR adds a simple (not secure) hashing function to solve the problem.

Stop using `window.btoa`, use a simple hashing function instead.

---

src/core.js

This PR addresses two low-hanging fixes that should greatly improve scrolling performance with `imgix.fluid({lazyLoad: true})`:
- Refactor URL-versioning to not require a call to `imgix.parseUrl()`
- Cache parsed URL objects in `FluidSet.getImgDetails()` to prevent instantiating a new `imgix.URL` object for each element on each scroll event.
To be clear: this branch is *not* sufficient in the long term. This scroll-handler code is still highly inefficient and very much in need of a rewrite, and fixing it the right way will probably have to wait until we rewrite the whole library. In this PR I'm just trying to patch things up to get some immediate performance improvements until we can dedicate the eng resources needed to do this right.
In my not-quite-scientific testing, I'm seeing call …

Low-hanging perf improvements for scroll handling

---

README.md

Although it might seem obvious, the `name` of the package is not always obvious. Most of times it is different, and some are the same as the repo name. I thought it was `imgix`, and unfortunately `npm` found a package named that way and installed. Took me 30 minutes to figure out...

Added fast installation instructions

---

src/core.js

This pull request adds checks to make sure the `crossorigin` attribute on `<img/>` tags is respected when making requests. This fixes a bug wherein images weren't being delivered with proper CORS headers.

Ensure `crossorigin` attribute is respected

---

src/core.js

(Original PR is at #57)
This PR ensures that if a URL contains a port, imgix.js won't strip it out when reconstructing the URL. This PR resolves #44.

Ensure port is retained when building a URL

---

src/polyfills.js

This PR removes the `console` polyfill we had been including, since it's not necessary at all.
Fixes #66

Removing the console polyfill

---

.travis.yml
Gruntfile.js
src/fluid.js
src/polyfills.js

This PR does two things:
- Removes the `Function.bind()` polyfill from imgix.js (only used in one place and easily replaced)
- Ensures that continuous-integration tests on Travis are run both with and without polyfills.
This PR will close #64

Remove `.bind()` polyfill and add `--no-polyfills` tests to CI

---

src/colors.js
src/fluid.js
src/url.js

When I carelessly removed the `console` polyfill in 74c5cfa, I failed to realize there were still calls to `console.warn` that made it into the distributable. This PR wraps those calls to make sure they don't break old or misunderstood browser.
This PR will close #72.

Making console calls safer

---

src/core.js

I've merged the little-used, less-needed `imgix.getRawBackgroundImage` method into the `imgix.getBackgroundImage` method. In addition, I updated the url-matching regex we're using (see issue #79) and improved our style-selection to use `getComputedStyle()` where possible, instead of just using `style.cssText`.
@lukechesser How's this look to you?

Improving background-image matching methods

---

dist/imgix.js
src/fluid.js
tests/fluid_test.js

Allows user to specify which elements should listen for scroll events. Defaults to `[window]` and any override is accepted as-is, meaning `window` is not added automatically. My thinking is that since it's probably an advanced use case, may as well give the user as much control as possible.
Let me know if you'd also like me to build the release/docs and bump version as part of this PR. Thanks!

Accept explicit scroll containers

---

dist/imgix.js
src/fluid.js

referencing window in a node module crashes node.

prevent crashing in node when doing server-side rendering

---

src/core.js

In Safari in particular, occasionally a second request occurs when the
target element src is updated.
Previously the callback is fired once the preload is complete, which in
the above scenario, is before the image is truly loaded and ready for
render.
This addresses issue #92.

onLoad Callback Timing Fix

---

README.md
spec/ImgixTagSpec.js
src/ImgixTag.js

This PR reverts 88d6fc4d2da5ff7c706cb04a3cde009475f2f73d and f68fb2a88d06de24a89d91b73512a61cee338f1d, in an attempt to iron out some confusion about base64 parameters once and for all.
The original implementation would auto-encode base-64 parameters when provided to the `ix-params` attribute. This was implemented in an attempt to make this library behave similarly to our other OSS libraries such as [imgix-core-js]() and [imgix-rb](https://github.com/imgix/imgix-rb). This behavior allows users to provide unencoded values for `foo64`-style parameters for the sake of convenience, auto-encoding the values as the URL is generated. There's an argument to be made that this is perhaps more confusing than it is convenient, but the issue was thoroughly argued and reasoned about before …

Fix ix-src b64 encoding issue

---

README.md
spec/ImgixTagSpec.js
spec/utilSpec.js
src/ImgixTag.js
src/imgix.js
src/util.js

As mentioned in #121, there's a case to be made for allowing imgix.js to skip setting attributes (`src`, `srcset`, `sizes`) when it runs. This PR adds logic (and removes some) to allow this to happen. If the `srcAttribute`, `srcsetAttribute`, or `sizesAttribute` config values are set to a falsy value (either directly, or through `<meta>` tags), the corresponding attribute will not be set on images represented by an `ImageTag` object.
@719media Would you mind reviewing this for me before I merge and release it?

Allow for skipping attribute-setting

---

src/targetWidths.js

This PR addresses an issue where, given a fractional `window.devicePixelRatio` (which can occur, for example, when a browser is zoomed to 90%), we can inadvertently add a non-integer width value to the end of an image tag's `sizes` list. While most browsers seem to handle this gracefully, and the imgix service itself handles fractional `w` and `h` value correctly (we simply floor the value to the nearest integer), this behavior chunders a lot of errors into the browser console. It's unsettling!
This fixes #126.

Don't allow a fractional maxScreenWidthRequired

---

spec/ImgixTagSpec.js
src/ImgixTag.js

This PR addresses a bug uncovered in `ImgixTag._extractBaseParams()`. When calling this method on an element that uses the `ix-src` attribute and does not include any query parameters in its base URL, it is expected that an empty object `{}` would be output. Instead, an object with a single property was being output, where the value of that property was `undefined` and the key was the input URL. This caused the original image URL to be included in the output `srcset` as a query parameter for all generated URLs.
For example, this caused an element such as `<img ix-src="http://example.com/foo.png">` to be assigned a `srcset` where all listed URLs began with `http://example.com/foo.png?http://example.com/foo.png=undefined&w=...`.
This PR includes a fix for this bug, plus an addition to the …

Fix bug in `ImgixTag._extractBaseParams()`

---

package.json
spec/ImgixTagSpec.js
src/targetWidths.js

This PR updates the srcset width-generation logic. The widths now grow exponentially, rather than by a fixed amount. This means that the dimensions of a  rendered image are at most 8% from the "pixel-perfect" dimensions. 
Ensure that tests still pass.

feat: use exponential increase for srcset widths

---

src/ImgixTag.js

Currently, this library supports value-less imgix parameters. For example, passing `{valueless: undefined, w: 20}` as options will create a URL like `...image.png?valueless&w=20`. Discussing internally at imgix, this behaviour is not supported, and so this PR removes this support.
Should this be a breaking change? My vote is no because it was never supported behaviour and shouldn't have done anything when passed to imgix, but happy to make it a breaking change if needed.
None.

fix: remove support for value-less search parameters

---

README.md
spec/ImgixTagSpec.js
src/ImgixTag.js
src/defaultConfig.js
src/imgix.js

This PR allows developers to set default parameters for every img tag. This prevents them from having to set the same parameters over and over again.
This fixes #129 
Review new unit tests.

feat: global default parameters

---

package-lock.json
package.json
spec/ImgixTagSpec.js
src/ImgixTag.js

This PR addresses two issues that can result in broken tags:
- Current validations do not catch instances of `ix-src=""` or `ix-path=""`, which can cause errors further down the line
- Throwing any error on failed validations will halt imgix.js from processing subsequent `img` or `picture` tags, even if they are valid. This PR circumvents this scenario by only processing an image if all validations are passed.

fix: skip over tags that fail validations

---

README.md

This PR restructures the header section of the README, adds more badges, and makes some edits to content and writing style. The header is wrapped in a tag that will exclude it from being displayed on the [imgix libraries](https://docs.imgix.com/libraries) page.

docs: restructure README header; style/text changes

---

README.md

Github doesn't parse nested links correctly, so I removed the nested link for the "lazyloading" TOC header
The TOC header was broken cause of a nested link. This PR removes the nested link:
Related issue: [e.g. #42]
Code:
```js
// A standalone example of what the PR solves
```

docs: fix TOC for lazyloading

---

cypress/integration/sizesAutoSpec.js
src/autoSize.js
src/util.js

This PR creates a debounce fn that better limits the amount updates to the `sizes` attribute made by `updateOnResize()`. It also removes custom attributes that are no longer needed, like `_ixWidth`.
The PR also adds tests cases to ensure the module waits for the debounce before updating the `sizes` attribute.

chore(debounce): add debounce fn and refactor raf

---

cypress/integration/metaSpec.js
cypress/integration/sizesAutoSpec.js
cypress/plugins/index.js
cypress/support/index.js
package-lock.json
package.json

This PR adds the `cypress-audit` plugin dev-dep and integrates it into the cypress tests to ensure package performance does not degrade as code gets added over time.

chore(dev-ceps): add cypress-audit

---

package-lock.json
package.json
src/util.js

This PR replaces the custom `debounce` function with [lodash's](https://lodash.com/docs/4.17.15#debounce) `_.debounce`.
This reduces our need to keep  the function up to date with the best practices around debouncing and introduces new functionality (leading vs trailing debouncing) that we can leverage.

chore(debounce): use lodash debounce package

---

package.json

I noticed in a previous release that we are not restricting which files/directories get published. This results in several non-essential files getting bundled in the release, which causes bloat for our end users. This PR fixes this issue by requiring files/directories to be opted in via the package.json [files](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) field. In this way, maintainers don't have to remember to update an opt-out list (such as `.gitignore`) when working on this library.
Note:
> Certain files are always included, regardless of settings:
>   package.json
README
CHANGES / CHANGELOG / HISTORY
LICENSE / LICENCE
NOTICE
The file in the "main" field
>
> README, CHANGES, LICENSE & NOTICE can have any case and extension.
Note 2: if you're ever unsure, you can …

build: limit which files are publish in a release

---

index.html

Browsers were blocking the image requests since the expected scheme,
https, did not match the src URL scheme, http. The meta property,
ix:useHttps, had to be set to "true" to fix this issue.

fix: change useHttps to true in demo file to fix blocked assets error

---

cypress/fixtures/index.html
cypress/integration/sizesAutoSpec.js
src/ImgixTag.js

This PR setts `sizes` from `ix-sizes` if it is set to a value that's not `'auto'`.
Addresses [this comment](https://github.com/imgix/imgix.js/pull/297#discussion_r636687300) on #297 ,

fix(sizes): use ix-sizes as sizes fallback if ix-sizes not auto

---

src/imgix.js

index.js had not been updated to relfect the currently released version
which was affecting out internal reporting for this version of the
library. This commit fixes the version number.

fix: bump version to match current

---

.gitignore
.travis.yml
package-lock.json
package.json

This PR adds semantic-release to all branches for this repository.
This PR brings in changes from `0ade8e7ba68e53d5adbcec5c09cacb82f5653f27` from `next` branch, with the exception that the `replace` plugin's replacement text is a regex rather than a string. This is a more reliable way to find and replace version numbers and more closely matches the semantic-release docs.

build: enable semantic-release in all branches

---

README.md

updated README to mention that `class=lazyload` should be included in image tag when using lazysizes

docs: updated lazyload section of README

---

README.md
spec/ImgixTagSpec.js
src/ImgixTag.js

Added an optional class 'nolazyload' that allows the end user to manually disable lazy loading for select elements when using lazysizes. The class functions by adding a simple manual override for the 'srcAttribute', 'srcsetAttribute', and 'sizesAttribute' settings, allowing the user to disable the 'data-*' settings both when using meta-tags and while setting the values with JavaScript. 
The current testing for the class consists of unit tests for the effect of 'nolazyload' with overridden attribute settings. Potential followup testing might include full integration tests for 'nolazyload' used in conjunction with the third party lazysizes library.

feat(imgixtag): add nolazyload class to selectively disable lazy loading

---

package.json

Semantic Release was configured to use double quotes for the version number so updated the config to use single quotes as is currently used in the library.

chore(deploy): configured semantic release config to use single quotes

---

cypress/integration/sizesAutoSpec.js

Skips brittle tests in `sizesAutoSpec.js`. Solutions for the underlying cause have been discussed offline, and work is planned on the issue - as such, we add a temporary fix to prevent CircleCI from blocking dependency updates.
Brittle tests in the `sizesAutoSpec.js` integration test file intermittently blocked PRs and dependency updates by Renovate.
Brittle tests in `sizesAutoSpec.js` are skipped, marked with a `TODO`.

test: add skip for brittle debounce tasks

---

spec/ImgixTagSpec.js
src/ImgixTag.js

This PR removes the logic in `ix-src` responsible for resizing the `h` (height) parameter to maintain aspect ratio when building the `srcset` attribute. With the help of the [imgix aspect ratio parameter](https://blog.imgix.com/2019/07/17/aspect-ratio-parameter-makes-cropping-even-easier), users can now achieve the same effect with the inclusion of the `ar` parameter. This should yield slightly better performance, code cleanliness, and bring the library more in line with the imgix API.
Please note, the `ar` parameter should also be used with `fit=crop` to take effect. 
----------
**Demo**
The following is an example of how to use the `ar` parameter in this library. More information on usage specifics can be found on the [imgix API docs](https://docs.imgix.com/apis/url/size/ar).
```js
<img …
```

chore: deprecate resizing the height param when maintaining aspect ratio

---

README.md

This PR adds a missing opening `html` bracket which is causing some syntax issues for the docs page
_Custom Input Attributes should not be in a html block, but the <img> tag should be_: 
The [imgix.js docs page](https://docs.imgix.com/libraries/imgix-js) is displaying `### Custom Input Attributes` incorrectly and chaining display issues:
This is also causing text on mobile screen to go off the page and the seo crawlers are throwing mobility view errors(frontend is investigating some crawler errors):
[Jira](https://imgix.atlassian.net/browse/PE-3192)

fix: adds a missing html tag

---

README.md

Correct readme instructions to use "&" instead of "&amp;" to chain parameters.
Same for output HTML code snippets.

fix(readme):remove html encoding from parameter strings
